### ISSUE TITLE
Option to update paths?

### ISSUE THREAD

**Issue by dubiousjim** [rptb1/aliasPath#2]
Hi, this is a nice tool, thanks for making it available. I notice while playing around with it, that unlike AppleScript-based methods for querying the path of the original, this tool keeps returning the path that the alias was created with. In some cases, if the alias is broken, that's what I want. In other cases it isn't. For instance, I might create an alias to a file at path A, then move that file to path B, then run this tool. It will still tell me path A. If I then use AppleScript to query the path of the original, it will tell me path B. At this point I assume the actual alias file has updated its path. But this tool continues to report path A. Is there any simple fix that would get this tool to resolve to the current path of the target file if available, else fall back to the path it's now reporting?

**Comment by rptb1** [comment]
The purpose of this tool is to return the path that the alias currently has stored. When you attempt to open an alias (including examining it with Applescript) the Alias Manager will update that path using other clues stored in the alias of the file has moved. You should attempt to examine the path with Applescript, then use this tool *if that fails* to help with fixing the alias yourself.
